language: node.js
cache:
  directories:
    - ~!@/.npm
node_js:
  - '9'
git:
  depth: 3
script: 
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: public/
  target-branch: master
  commit_message: "Deploy release ${TRAVIS_TAG}"
  on:
    branch: master             
