language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build
git:
  depth: 3
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  project: ./build/
  commit_message: "Deploy release ${TRAVIS_TAG}"
on:
  branch: master
